Lang['bg'] = {
  -- Общ
  ['OnlyAdmins'] = 'Тази функция е само за администратори!',

  -- Пиано
  ['PlayPiano_Play'] = 'Натиснете [~e~ Space ~q~], за да свирите на пиано',
  ['PlayPiano_Stop'] = 'Натиснете [~e~ F ~q~], за да спрете да играете',

  -- Метаболизъм
  ['Metabolism_IFCC'] = 'Неправилен_Format_Check_Config',
  ['Metabolism_YourDying1'] = 'Умирате, проверете жизнените си показатели!',
  ['Metabolism_YourDying2'] = 'Чувствам изтръпване в пръстите ...',
  ['Metabolism_YourDying3'] = 'Виждам светлините, краят е близо ...',

  -- UsableItems
  ['UsableItems_NoTent'] = 'Вие нямате палатка!',
  ['UsableItems_NoCampFire'] = 'Нямате огън!',
  ['UsableItems_PlacingCampfire'] = "Поставяте лагерния си огън ...",
  ['UsableItems_PlacingTent'] = "Поставяте палатката си ...",
  ['UsableItems_Eating'] = "Вие сте консумирали",
  ['UsableItems_Drinking'] = "Пили сте",
  ['UsableItems_RefundCampfire'] = "Върнаха ви лагерния огън",
  ['UsableItems_RefundTent'] = "Възстановена ви е палатка",

  -- Магазини
  ['Store_OpenShop'] = 'Натиснете [~e~ SPACE ~q~], за да отворите менюто на магазина',
  ['Store_MenuTitle'] = 'Общ магазин',
  ['Store_Category'] = 'Категория',
  ['Store_Buy'] = 'Купуване на артикули',
  ['Store_Sell'] = 'Продавайте артикули',
  ['Store_Food'] = 'Храна',
  ['Store_Meds'] = 'Медицински',
  ['Store_Misc'] = 'Разни',
  ['Store_FoodMenu'] = 'Меню за храна',
  ['Store_MedsMenu'] = 'Медицински артикули',
  ['Store_MiscMenu'] = 'Други елементи',
  ['Store_FoodSubTitle'] = 'Вашите ежедневни основни нужди',
  ['Store_MedsSubTitle'] = 'За да останеш жив!',
  ['Store_OtherItems'] = 'Други елементи',
  ['Store_NotEnoughMoney'] = 'Няма достатъчно пари',
  ['Store_Bought1'] = "Купихте",
  ['Store_Bought2'] = ', струва ви $',
  ['Store_Bought3'] = 'Долар!',
  ['Store_Sold'] = "Продали сте артикул:",
  ['Store_NoItem'] = "Нямате елемент, наречен:",

  -- Ловец на глави
  ['BountyHunter_PressSpace'] = 'Натиснете [~e~ SPACE ~q~], за да отворите менюто за награди',
  ['BountyHunter_MenuTitle'] = 'Bounty Board',
  ['BountyHunter_PVESubTitle'] = 'Лов на NPC',
  ['BountyHunter_PVPSubTitle'] = 'Лов на хора',
  ['BountyHunter_PVEMenu'] = 'PVE меню',
  ['BountyHunter_PVPMenu'] = 'PVP меню',
  ['BountyHunter_HuntBountyButton'] = 'Намиране на награда',
  ['BountyHunter_ReceivePayment'] = 'Получаване на плащане',
  ['BountyHunter_NoBounties'] = "Нямате записани убийства на глави, партньоре!",
  ['BountyHunter_SetBounty'] = 'Задаване на награда',
  ['BountyHunter_Payment1'] = "Получихте $",
  ['BountyHunter_Payment2'] = 'и',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = 'Вашата награда се намира на картата!',
  ['BountyHunter_TheyBeDead'] = 'Трябват ни мъртви, а не живи! Но мъртъв! ',
  ['BountyHunter_StackBounties'] = 'Можете да подреждате награди, само имайте предвид',
  ['BountyHunter_DieAndLose'] = 'че губите наградите, ако сте умрели!',
  ['BountyHunter_KilledAllTargets'] = 'Успяхте да убиете всички цели',
  ['BountyHunter_SearchBodies'] = 'Търсете доказателства в телата,',
  ['BountyHunter_AndBringBack'] = 'и върнете това обратно в полицейския офис!',
  ['BountyHunter_BringBackEvidence'] = 'Върнете доказателствата в шериф!',
  ['BountyHunter_LostTargets'] = "Изгубихте целите си",
}
