Lang['es'] = {
  -- general
  ['OnlyAdmins'] = '¡Esta función es solo para administradores!',

  -- Piano
  ['PlayPiano_Play'] = 'Presione [~e~ Espacio ~q~] para tocar el piano',
  ['PlayPiano_Stop'] = 'Presione [~e~ F ~q~] para detener la reproducción',

  -- Metabolismo
  ['Metabolism_IFCC'] = 'Configuración_de_verificación_de_formato_incorrecta',
  ['Metabolism_YourDying1'] = '¡Te estás muriendo, revisa tus signos vitales!',
  ['Metabolism_YourDying2'] = 'Siento un hormigueo en mis dedos ...',
  ['Metabolism_YourDying3'] = 'Puedo ver las luces, el final está cerca ...',

  -- Elementos utilizables
  ['UsableItems_NoTent'] = '¡No tienes tienda!',
  ['UsableItems_NoCampFire'] = '¡No tienes fogata!',
  ['UsableItems_PlacingCampfire'] = "Estás colocando tu fogata ...",
  ['UsableItems_PlacingTent'] = "Estás colocando tu tienda ...",
  ['UsableItems_Eating'] = "Has consumido",
  ['UsableItems_Drinking'] = "Has bebido",
  ['UsableItems_RefundCampfire'] = "Te reembolsaron una fogata",
  ['UsableItems_RefundTent'] = "Se le reembolsó una tienda de campaña",

  -- Historias
  ['Store_OpenShop'] = 'Presione [~e~ SPACE ~q~] para abrir el menú de la tienda',
  ['Store_MenuTitle'] = 'Tienda general',
  ['Store_Category'] = 'Categoría',
  ['Store_Buy'] = 'Comprar artículos',
  ['Store_Sell'] = 'Vender artículos',
  ['Store_Food'] = 'Comida',
  ['Store_Meds'] = 'Médico',
  ['Store_Misc'] = 'Varios',
  ['Store_FoodMenu'] = 'Menú de comida',
  ['Store_MedsMenu'] = 'Artículos médicos',
  ['Store_MiscMenu'] = 'Otros artículos',
  ['Store_FoodSubTitle'] = 'Tus necesidades básicas diarias',
  ['Store_MedsSubTitle'] = '¡Por seguir con vida!',
  ['Store_OtherItems'] = 'Otros artículos',
  ['Store_NotEnoughMoney'] = 'No hay suficiente dinero',
  ['Store_Bought1'] = "Has comprado un",
  ['Store_Bought2'] = ', le cuesta $',
  ['Store_Bought3'] = '¡Dólar!',
  ['Store_Sold'] = "Has vendido un artículo:",
  ['Store_NoItem'] = "No tiene ningún elemento llamado:",

  -- Cazarrecompensas
  ['BountyHunter_PressSpace'] = 'Presione [~e~ SPACE ~q~] para abrir el menú de recompensas',
  ['BountyHunter_MenuTitle'] = 'Tablero de recompensas',
  ['BountyHunter_PVESubTitle'] = 'Cazar NPC',
  ['BountyHunter_PVPSubTitle'] = 'Cazar humanos',
  ['BountyHunter_PVEMenu'] = 'Menú PVE',
  ['BountyHunter_PVPMenu'] = 'Menú PVP',
  ['BountyHunter_HuntBountyButton'] = 'Caza una recompensa',
  ['BountyHunter_ReceivePayment'] = 'Recibir pago',
  ['BountyHunter_NoBounties'] = "¡No tienes bajas por recompensa registradas, socio!",
  ['BountyHunter_SetBounty'] = 'Establecer una recompensa',
  ['BountyHunter_Payment1'] = "Recibiste $",
  ['BountyHunter_Payment2'] = 'y',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = '¡Tu recompensa está ubicada en el mapa!',
  ['BountyHunter_TheyBeDead'] = '¡Los necesitamos muertos, no vivos! ¡Pero muerto! ',
  ['BountyHunter_StackBounties'] = 'Puede acumular recompensas, solo tenga en cuenta',
  ['BountyHunter_DieAndLose'] = '¡que pierdes las recompensas si mueres!',
  ['BountyHunter_KilledAllTargets'] = 'Lograste matar a todos los objetivos',
  ['BountyHunter_SearchBodies'] = 'Buscar pruebas en los cuerpos,',
  ['BountyHunter_AndBringBack'] = '¡y llévate esto a la oficina de policía!',
  ['BountyHunter_BringBackEvidence'] = '¡Devuélvele la evidencia al sherrif!',
  ['BountyHunter_LostTargets'] = "Has perdido tus objetivos",
}
