Lang['fr'] = {
  -- Général
  ['OnlyAdmins'] = 'Cette fonctionnalité est réservée aux administrateurs!',

  -- Piano
  ['PlayPiano_Play'] = 'Appuyez sur [~e~barre d\'espace~q~] pour jouer du piano',
  ['PlayPiano_Stop'] = 'Appuyez sur [~e~F~q~] pour arrêter la lecture',

  -- Métabolisme
  ['Metabolism_IFCC'] = 'Configuration_de_vérification_du_format_incorrecte',
  ['Metabolism_YourDying1'] = 'Vous êtes en train de mourir, vérifiez vos signes vitaux!',
  ['Metabolism_YourDying2'] = 'Je sens des picotements dans mes doigts ...',
  ['Metabolism_YourDying3'] = 'Je peux voir les lumières, la fin est proche ...',

  -- Articles utilisables
  ['UsableItems_NoTent'] = 'Vous n\'avez pas de tente! ',
  ['UsableItems_NoCampFire'] = 'Vous n\'avez pas de feu de camp! ',
  ['UsableItems_PlacingCampfire'] = "Vous placez votre feu de camp ...",
  ['UsableItems_PlacingTent'] = "Vous placez votre tente ...",
  ['UsableItems_Eating'] = "Vous avez consommé",
  ['UsableItems_Drinking'] = "Vous avez bu",
  ['UsableItems_RefundCampfire'] = "Un feu de camp vous a été remboursé",
  ['UsableItems_RefundTent'] = "Une tente vous a été remboursée",

  -- Magasins
  ['Store_OpenShop'] = 'Appuyez sur [~e~ESPACE~q~] pour ouvrir le menu de la boutique',
  ['Store_MenuTitle'] = 'Magasin général',
  ['Store_Category'] = 'Catégorie',
  ['Store_Buy'] = 'Acheter des articles',
  ['Store_Sell'] = 'Vendre des articles',
  ['Store_Food'] = 'Nourriture',
  ['Store_Meds'] = 'Médical',
  ['Store_Misc'] = 'Divers',
  ['Store_FoodMenu'] = 'Menu Nourriture',
  ['Store_MedsMenu'] = 'Articles médicaux',
  ['Store_MiscMenu'] = 'Autres éléments',
  ['Store_FoodSubTitle'] = 'Vos besoins de base quotidiens',
  ['Store_MedsSubTitle'] = 'Pour rester en vie!',
  ['Store_OtherItems'] = 'Autres articles',
  ['Store_NotEnoughMoney'] = 'Pas assez d\'argent',
  ['Store_Bought1'] = "Vous avez acheté un",
  ['Store_Bought2'] = ', ça vous coûte $',
  ['Store_Bought3'] = 'Dollar!',
  ['Store_Sold'] = "Vous avez vendu un article:",
  ['Store_NoItem'] = "Vous n'avez aucun élément appelé:",

  -- Chasseur de primes
  ['BountyHunter_PressSpace'] = 'Appuyez sur [~e~ESPACE~q~] pour ouvrir le menu des primes',
  ['BountyHunter_MenuTitle'] = 'Tableau de primes',
  ['BountyHunter_PVESubTitle'] = 'Chasser les PNJ',
  ['BountyHunter_PVPSubTitle'] = 'Chasser les humains',
  ['BountyHunter_PVEMenu'] = 'Menu PVE',
  ['BountyHunter_PVPMenu'] = 'Menu PVP',
  ['BountyHunter_HuntBountyButton'] = 'Chasser une prime',
  ['BountyHunter_ReceivePayment'] = 'Recevoir le paiement',
  ['BountyHunter_NoBounties'] = "Vous n'avez pas enregistré de victimes de primes, partenaire!",
  ['BountyHunter_SetBounty'] = 'Définir une prime',
  ['BountyHunter_Payment1'] = "Vous avez reçu $",
  ['BountyHunter_Payment2'] = 'et',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = 'Votre prime est localisée sur la carte!',
  ['BountyHunter_TheyBeDead'] = 'Nous avons besoin d\'eux morts, pas vivants! Mais mort! ',
  ['BountyHunter_StackBounties'] = 'Vous pouvez empiler des primes, gardez juste à l\'esprit',
  ['BountyHunter_DieAndLose'] = 'que vous perdez les primes si vous mourez!',
  ['BountyHunter_KilledAllTargets'] = 'Vous avez réussi à tuer toutes les cibles',
  ['BountyHunter_SearchBodies'] = 'Rechercher des preuves dans les corps,',
  ['BountyHunter_AndBringBack'] = 'et ramenez ceci au bureau de police!',
  ['BountyHunter_BringBackEvidence'] = 'Rapportez les preuves au sherrif!',
  ['BountyHunter_LostTargets'] = "Vous avez perdu vos cibles",
  ['BountyHunter_NoStackAllowed'] = "Vous avez déjà une prime active! Tuez-les d'abord",
  ['BountyHunter_MaxBountiesReached'] = "Vous avez trop de primes ouvertes, tuez-les d'abord",

  ['PickableFruits_PressSpace'] = 'Appuyez sur [~e~SPACE~q~] pour récolter les baies',
  ['PickableFruits_Searching'] = "Recherche ...",
  ['PickableFruits_Collected'] = "Vous avez collecté",
  ['PickableFruits_NothingFound'] = "Il n'y a rien à collecter ici!",
  ['PickableFruits_NothingFound'] = "Il n'y a rien à collecter ici!",

  ['Rivers_Info'] = "Appuyez sur [~e~G~q~] pour laver, [~e~ENTER~q~] pour boire de l'eau",
}
