Lang['gr'] = {
  -- Γενικά
  ['OnlyAdmins'] = 'Αυτή η λειτουργία είναι μόνο για διαχειριστές!',

  -- πιάνο
  ['PlayPiano_Play'] = 'Πατήστε [~e~ Space ~q~] για να παίξετε πιάνο',
  ['PlayPiano_Stop'] = 'Πατήστε [~e~ F ~q~] για να σταματήσετε να παίζετε',

  -- Μεταβολισμός
  ['Metabolism_IFCC'] = 'Εσφαλμένο_Format_Check_Config',
  ['Metabolism_YourDying1'] = 'Πεθαίνετε, ελέγξτε τα ζωτικά σας!',
  ['Metabolism_YourDying2'] = "Νιώθω μυρμήγκιασμα στα δάχτυλά μου ...",
  ['Metabolism_YourDying3'] = 'Μπορώ να δω τα φώτα, το τέλος είναι κοντά ...',

  -- Στοιχεία που μπορούν να χρησιμοποιηθούν
  ['UsableItems_NoTent'] = 'Δεν έχετε σκηνή!',
  ['UsableItems_NoCampFire'] = 'Δεν έχετε φωτιά!',
  ['UsableItems_PlacingCampfire'] = "Τοποθετείτε τη φωτιά σας ...",
  ['UsableItems_PlacingTent'] = "Τοποθετείτε τη σκηνή σας ...",
  ['UsableItems_Eating'] = "Έχετε καταναλώσει",
  ['UsableItems_Drinking'] = "Έχετε πιει",
  ['UsableItems_RefundCampfire'] = "Σας έχει επιστραφεί μια πυρά προσκόπων",
  ['UsableItems_RefundTent'] = "Σας έχει επιστραφεί μια σκηνή",

  -- Καταστήματα
  ['Store_OpenShop'] = 'Πατήστε [~e~ SPACE ~q~] για να ανοίξετε το μενού καταστήματος',
  ['Store_MenuTitle'] = "Γενικό κατάστημα",
  ['Store_Category'] = 'Κατηγορία',
  ['Store_Buy'] = 'Αγορά αντικειμένων',
  ['Store_Sell'] = 'Πώληση αντικειμένων',
  ['Store_Food'] = "Φαγητό",
  ['Store_Meds'] = 'Ιατρική',
  ['Store_Misc'] = 'Διάφορα',
  ['Store_FoodMenu'] = 'Μενού φαγητού',
  ['Store_MedsMenu'] = 'Ιατρικά είδη',
  ['Store_MiscMenu'] = 'Άλλα αντικείμενα',
  ['Store_FoodSubTitle'] = "Οι καθημερινές σας βασικές ανάγκες",
  ['Store_MedsSubTitle'] = 'Για να μένεις ζωντανός!',
  ['Store_OtherItems'] = 'Άλλα αντικείμενα',
  ['Store_NotEnoughMoney'] = 'Δεν είναι αρκετά χρήματα',
  ['Store_Bought1'] = "Αγοράσατε ένα",
  ['Store_Bought2'] = ', σας κοστίζει $',
  ['Store_Bought3'] = 'Δολάριο!',
  ['Store_Sold'] = "Έχετε πουλήσει ένα αντικείμενο:",
  ['Store_NoItem'] = "Δεν έχετε όνομα με το όνομα:",

  -- Κυνηγός επικυρηγμένων
  ['BountyHunter_PressSpace'] = 'Πατήστε [~e~ SPACE ~q~] για να ανοίξετε το μενού bounty',
  ['BountyHunter_MenuTitle'] = 'Bounty Board',
  ['BountyHunter_PVESubTitle'] = 'Κυνήγι NPC',
  ['BountyHunter_PVPSubTitle'] = "Κυνήγι ανθρώπων",
  ['BountyHunter_PVEMenu'] = 'Μενού PVE',
  ['BountyHunter_PVPMenu'] = 'Μενού PVP',
  ['BountyHunter_HuntBountyButton'] = 'Κυνήγι Bounty',
  ['BountyHunter_ReceivePayment'] = 'Λήψη πληρωμής',
  ['BountyHunter_NoBounties'] = "Δεν έχετε καταγράψει bounty kill, συνεργάτη!",
  ['BountyHunter_SetBounty'] = 'Ορίστε ένα Bounty',
  ['BountyHunter_Payment1'] = "Λάβατε $",
  ['BountyHunter_Payment2'] = 'και',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = "Το Bounty σας βρίσκεται στον χάρτη!",
  ['BountyHunter_TheyBeDead'] = 'Τους χρειαζόμαστε νεκρούς, όχι ζωντανούς! Αλλά νεκρός!',
  ['BountyHunter_StackBounties'] = "Μπορείτε να στοίβατε bounties, απλώς να έχετε κατά νου",
  ['BountyHunter_DieAndLose'] = 'ότι θα χάσεις τα γενναιοδωρία αν πεθάνεις!',
  ['BountyHunter_KilledAllTargets'] = "Καταφέρατε να σκοτώσετε όλους τους στόχους",
  ['BountyHunter_SearchBodies'] = 'Αναζητήστε αποδεικτικά στοιχεία στα σώματα',
  ['BountyHunter_AndBringBack'] = 'και επιστρέψτε το στο γραφείο της αστυνομίας!',
  ['BountyHunter_BringBackEvidence'] = 'Επιστρέψτε τα αποδεικτικά στοιχεία στον sherrif!',
  ['BountyHunter_LostTargets'] = "Έχετε χάσει τους στόχους σας",
}
