Lang['pl'] = {
  -- Γενικά
  ['OnlyAdmins'] = 'Αυτή η λειτουργία είναι μόνο για διαχειριστές!',

  -- πιάνο
  ['PlayPiano_Play'] = 'Πατήστε [~e~ Space ~q~] για να παίξετε πιάνο',
  ['PlayPiano_Stop'] = 'Πατήστε [~e~ F ~q~] για να σταματήσετε να παίζετε',

  -- Μεταβολισμός
  ['Metabolism_IFCC'] = 'Εσφαλμένο_Format_Check_Config',
  ['Metabolism_YourDying1'] = 'Πεθαίνετε, ελέγξτε τα ζωτικά σας!',
  ['Metabolism_YourDying2'] = "Νιώθω μυρμήγκιασμα στα δάχτυλά μου ...",
  ['Metabolism_YourDying3'] = 'Μπορώ να δω τα φώτα, το τέλος είναι κοντά ...',

  -- Στοιχεία που μπορούν να χρησιμοποιηθούν
  ['UsableItems_NoTent'] = 'Δεν έχετε σκηνή!',
  ['UsableItems_NoCampFire'] = 'Δεν έχετε φωτιά!',
  ['UsableItems_PlacingCampfire'] = "Τοποθετείτε τη φωτιά σας ...",
  ['UsableItems_PlacingTent'] = "Τοποθετείτε τη σκηνή σας ...",
  ['UsableItems_Eating'] = "Έχετε καταναλώσει",
  ['UsableItems_Drinking'] = "Έχετε πιει",
  ['UsableItems_RefundCampfire'] = "Σας έχει επιστραφεί μια πυρά προσκόπων",
  ['UsableItems_RefundTent'] = "Σας έχει επιστραφεί μια σκηνή",

  -- Καταστήματα
  ['Store_OpenShop'] = 'Πατήστε [~e~ SPACE ~q~] για να ανοίξετε το μενού καταστήματος',
  ['Store_MenuTitle'] = "Γενικό κατάστημα",
  ['Store_Category'] = 'Κατηγορία',
  ['Store_Buy'] = 'Αγορά αντικειμένων',
  ['Store_Sell'] = 'Πώληση αντικειμένων',
  ['Store_Food'] = "Φαγητό",
  ['Store_Meds'] = 'Ιατρική',
  ['Store_Misc'] = 'Διάφορα',
  ['Store_FoodMenu'] = 'Μενού φαγητού',
  ['Store_MedsMenu'] = 'Ιατρικά είδη',
  ['Store_MiscMenu'] = 'Άλλα αντικείμενα',
  ['Store_FoodSubTitle'] = "Οι καθημερινές σας βασικές ανάγκες",
  ['Store_MedsSubTitle'] = 'Για να μένεις ζωντανός!',
  ['Store_OtherItems'] = 'Άλλα αντικείμενα',
  ['Store_NotEnoughMoney'] = 'Δεν είναι αρκετά χρήματα',
  ['Store_Bought1'] = "Αγοράσατε ένα",
  ['Store_Bought2'] = ', σας κοστίζει $',
  ['Store_Bought3'] = 'Δολάριο!',
  ['Store_Sold'] = "Έχετε πουλήσει ένα αντικείμενο:",
  ['Store_NoItem'] = "Δεν έχετε όνομα με το όνομα:",

  -- Łowca nagród
  ['BountyHunter_PressSpace'] = 'Naciśnij [~e~ SPACE ~q~], aby otworzyć menu nagród',
  ['BountyHunter_MenuTitle'] = 'Tablica zleceń',
  ['BountyHunter_PVESubTitle'] = 'Poluj na NPC',
  ['BountyHunter_PVPSubTitle'] = 'Poluj na ludzi',
  ['BountyHunter_PVEMenu'] = 'Menu PVE',
  ['BountyHunter_PVPMenu'] = 'Menu PVP',
  ['BountyHunter_HuntBountyButton'] = 'Poluj na nagrodę',
  ['BountyHunter_ReceivePayment'] = 'Odbierz płatność',
  ['BountyHunter_NoBounties'] = "Nie masz żadnych nagranych zabójstw, partnerze!",
  ['BountyHunter_SetBounty'] = 'Ustaw nagrodę',
  ['BountyHunter_Payment1'] = "Otrzymałeś $",
  ['BountyHunter_Payment2'] = 'i',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = 'Twoja nagroda znajduje się na mapie!',
  ['BountyHunter_TheyBeDead'] = 'Potrzebujemy ich martwych, a nie żywych! Ale martwy! ',
  ['BountyHunter_StackBounties'] = 'Możesz kumulować nagrody, pamiętaj o tym',
  ['BountyHunter_DieAndLose'] = 'że tracisz nagrody, jeśli zginąłeś!',
  ['BountyHunter_KilledAllTargets'] = 'Udało ci się zabić wszystkie cele',
  ['BountyHunter_SearchBodies'] = 'Przeszukaj ciała w poszukiwaniu dowodów,',
  ['BountyHunter_AndBringBack'] = 'i wróć do biura policji!',
  ['BountyHunter_BringBackEvidence'] = 'Przynieś dowody szeryfowi!',
  ['BountyHunter_LostTargets'] = "Straciłeś swoje cele",
}
