Lang['ru'] = {
  -- Общий
  ['OnlyAdmins'] = 'Эта функция предназначена только для администраторов!',

  -- piano
  ['PlayPiano_Play'] = 'Нажмите [~e~пробел~q~], чтобы играть на пианино',
  ['PlayPiano_Stop'] = 'Нажмите [~e~F~q~], чтобы остановить воспроизведение',

  -- метаболизм
  ['Metabolism_IFCC'] = 'Неправильная_конфигурация_проверки_формата',
  ['Metabolism_YourDying1'] = 'Вы умираете, проверьте свои жизненно важные органы!',
  ['Metabolism_YourDying2'] = 'Я чувствую покалывание в пальцах ...',
  ['Metabolism_YourDying3'] = 'Я вижу огни, конец близок ...',

  -- UsableItems
  ['UsableItems_NoTent'] = 'У вас нет палатки!',
  ['UsableItems_NoCampFire'] = 'У вас нет костра!',
  ['UsableItems_PlacingCampfire'] = "Вы разводите костер ...",
  ['UsableItems_PlacingTent'] = "Вы ставите палатку ...",
  ['UsableItems_Eating'] = "Вы выпили",
  ['UsableItems_Drinking'] = "Вы выпили",
  ['UsableItems_RefundCampfire'] = "Вам вернули деньги на костер",
  ['UsableItems_RefundTent'] = "Вам вернули деньги за палатку",

  -- Магазины
  ['Store_OpenShop'] = 'Нажмите [~e~SPACE~q~], чтобы открыть меню магазина',
  ['Store_MenuTitle'] = 'Универсальный магазин',
  ['Store_Category'] = 'Категория',
  ['Store_Buy'] = 'Купить товары',
  ['Store_Sell'] = 'Продавать предметы',
  ['Store_Food'] = 'Еда',
  ['Store_Meds'] = 'Медицинский',
  ['Store_Misc'] = 'Разное',
  ['Store_FoodMenu'] = 'Меню еды',
  ['Store_MedsMenu'] = 'Медицинские товары',
  ['Store_MiscMenu'] = 'Другие элементы',
  ['Store_FoodSubTitle'] = 'Ваши повседневные базовые потребности',
  ['Store_MedsSubTitle'] = 'За то, чтобы остаться в живых!',
  ['Store_OtherItems'] = 'Другие элементы',
  ['Store_NotEnoughMoney'] = 'Недостаточно денег',
  ['Store_Bought1'] = "Вы купили",
  ['Store_Bought2'] = ', стоит вам $',
  ['Store_Bought3'] = 'Доллар!',
  ['Store_Sold'] = "Вы продали товар:",
  ['Store_NoItem'] = "У вас нет элемента с названием:",
  ['Store_Exit'] = 'Выход',
  
  -- Охотник за головами
  ['BountyHunter_PressSpace'] = 'Нажмите [~e~SPACE~q~], чтобы открыть меню наград',
  ['BountyHunter_MenuTitle'] = 'Доска объявлений',
  ['BountyHunter_PVESubTitle'] = 'Охота на NPC',
  ['BountyHunter_PVPSubTitle'] = 'Охота на людей',
  ['BountyHunter_PVEMenu'] = 'Меню PVE',
  ['BountyHunter_PVPMenu'] = 'Меню PVP',
  ['BountyHunter_HuntBountyButton'] = 'Охота за наградой',
  ['BountyHunter_ReceivePayment'] = 'Получить платеж',
  ['BountyHunter_NoBounties'] = "У вас нет зарегистрированных убийств за награду, партнер!",
  ['BountyHunter_SetBounty'] = 'Установить награду',
  ['BountyHunter_Payment1'] = "Вы получили $",
  ['BountyHunter_Payment2'] = 'и',
  ['BountyHunter_Payment3'] = 'XP',
  ['BountyHunter_BountyOnMap'] = 'Ваша награда указана на карте!',
  ['BountyHunter_TheyBeDead'] = 'Они нужны нам мертвыми, а не живыми! Но мертв! ',
  ['BountyHunter_StackBounties'] = 'Вы можете складывать награды, помните',
  ['BountyHunter_DieAndLose'] = 'что вы потеряете награды, если умрете!',
  ['BountyHunter_KilledAllTargets'] = 'Вам удалось убить все цели',
  ['BountyHunter_SearchBodies'] = 'Обыскать тела в поисках улик,',
  ['BountyHunter_AndBringBack'] = 'и отправь это обратно в полицию!',
  ['BountyHunter_BringBackEvidence'] = 'Верните доказательства шерифу!',
  ['BountyHunter_LostTargets'] = "Вы потеряли свои цели",
  ['BountyHunter_NoStackAllowed'] = "У вас уже есть активная награда! Сначала убейте их",
  ['BountyHunter_MaxBountiesReached'] = "У вас открыто много наград, сначала убейте их",

  ['PickableFruits_PressSpace'] = 'Нажмите [~e~ SPACE ~q~], чтобы собрать ягоды ',
  ['PickableFruits_Searching'] = "Поиск ...",
  ['PickableFruits_Collected'] = 'Вы собрали',
  ['PickableFruits_NothingFound'] = "Здесь нечего собирать!",

  ['Rivers_Info'] = "Нажмите [~e~G~q~], чтобы мыть, [~e~ENTER~q~], чтобы пить воду",
}
